services:
  - type: web
    name: claimsense-ai
    env: python
    buildCommand: apt-get install -y poppler-utils && pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: GOOGLE_VISION_KEY
        sync: false
